# Generated by Django 5.2.3 on 2025-07-27 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Select semester', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.semester'),
        ),
    ]
