# Generated by Django 5.2.3 on 2025-08-03 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_semester_material_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='department',
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select material category', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.category'),
        ),
    ]
